sudo: false

language: cpp

compiler:
  - gcc
#  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

cache:
  directories:
    - .cmake
    - .qt

before_script:
  # Fetch and install dependencies if cache miss
  - curl https://raw.githubusercontent.com/hawaii-desktop/repotools/master/ci/fetch-cmake | bash -x
  - curl https://raw.githubusercontent.com/hawaii-desktop/repotools/master/ci/fetch-qt | bash -x
  - export PATH=`pwd`/.cmake/bin:`pwd`/.qt/5.7/5.7/gcc_64/bin:$PATH
  - export LD_LIBRARY_PATH=`pwd`/.qt/5.7/5.7/gcc_64/lib:$LD_LIBRARY_PATH
  - export CMAKE_PREFIX_PATH=`pwd`/.qt/5.7/5.7/gcc_64/lib/cmake
  # Setup compilers
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  # xvfb for unit tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # prepare
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make check

notifications:
  email: false
  slack: qmlos:fdUqVmPzqPskEL1UBhqapZ0w
